### ISSUE TITLE
Ios pod Install Command

### ISSUE THREAD

**Issue by mortezasojodi** [GameAnalytics/GA-SDK-FLUTTER#1]
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/morteza/Desktop/varzeshgah/VarzeshgahNew/ios/Pods/GA-SDK-IOS/GameAnalytics.framework)
how can i fix it?
i follow flutter sdk setup

**Comment by the1schwartz** [comment]
Comment out `use_frameworks!` in the PodFile like here:

```
target 'Runner' do
  #use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by tavangar79** [comment]
It's better to use `:linkage => :static` in the Podfile like here:

```ruby
target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
